Updates

diff --git a/custom_kernel/run b/custom_kernel/run
--- a/custom_kernel/run
+++ b/custom_kernel/run
@@ -4,24 +4,21 @@ set -ex
 # Build Kernel
 # Build C and ASM
 nasm -f elf64 src/asm/utils.asm -o src/asm/utils.o
+nasm -f elf64 src/asm/boot.asm -o src/asm/boot.o
 gcc -c src/c/hardware.c -o src/c/hardware.o -ffreestanding -mno-red-zone -mcmodel=kernel -fno-pic
 
 # Build Kernel
 echo "Building Kernel..."
-CARGO_TARGET_X86_64_UNKNOWN_NONE_RUSTFLAGS="-C code-model=kernel -C relocation-model=static -C link-arg=-Tlinker.ld -C link-arg=src/asm/utils.o -C link-arg=src/c/hardware.o" cargo build --release --target x86_64-unknown-none || { echo "Cargo build failed"; exit 1; }
+CARGO_TARGET_X86_64_UNKNOWN_NONE_RUSTFLAGS="-C code-model=kernel -C relocation-model=static -C link-arg=-Tlinker.ld -C link-arg=src/asm/boot.o -C link-arg=src/asm/utils.o -C link-arg=src/c/hardware.o" cargo build --release --target x86_64-unknown-none || { echo "Cargo build failed"; exit 1; }
 
 # Build ISO
 echo "Building ISO..."
 rm -rf iso_root
-mkdir -p iso_root
-cp -v target/x86_64-unknown-none/release/ainux_kernel iso_root/
-cp -v limine.cfg limine/limine-bios.sys limine/limine-bios-cd.bin limine/limine-uefi-cd.bin iso_root/
+mkdir -p iso_root/boot/grub
+cp -v target/x86_64-unknown-none/release/ainux_kernel iso_root/boot/
+cp -v grub.cfg iso_root/boot/grub/ || :
 
-xorriso -as mkisofs -b limine-bios-cd.bin \
-        -no-emul-boot -boot-load-size 4 -boot-info-table \
-        --efi-boot limine-uefi-cd.bin \
-        -efi-boot-part --efi-boot-image --protective-msdos-label \
-        iso_root -o ainux.iso || { echo "ISO creation failed"; exit 1; }
+grub-mkrescue -o ainux.iso iso_root || { echo "ISO creation failed"; exit 1; }
 
 # Create Disk Image (EXT4) if not exists
 # Create Disk Image (EXT4) if not exists
